dependencies:
  cache_directories:
    - "~/.stack"
  pre:
    - wget https://www.stackage.org/stack/linux-x86_64-static -O /tmp/stack.gz
    - gunzip /tmp/stack.gz && chmod +x /tmp/stack
    - sudo mv /tmp/stack /usr/bin/stack
  override:
    - stack setup
    - stack build

test:
  override:
    - stack test
